apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deployment
spec:
  selector:
    matchLabels:
      app: userservice
  replicas: 1
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
      - name: userservice
        image: nginx
        ports:
        - containerPort: 80
