apiVersion: v1
kind: Service
metadata:
  name: userservice-service
  labels:
    app: userservice
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: userservice
